### ISSUE TITLE
simulation the traffic_light_recognition

### ISSUE THREAD

**Issue by liuypcoding** [yukkysaito/godot_rviz2#1]
Great! I had make it success!! but how can we simulation the traffic_light_recognition  Thanks.

**Comment by yukkysaito** [comment]
This is made as a visualization tool, not a simulator.
It is not difficult to visualize the traffic_light_recognition results as well, so please wait a little.

**Comment by liuypcoding** [comment]
> This is made as a visualization tool, not a simulator. It is not difficult to visualize the traffic_light_recognition results as well, so please wait a little.
> 
> Also, I will update how to build more easy



> This is made as a visualization tool, not a simulator. It is not difficult to visualize the traffic_light_recognition results as well, so please wait a little.
> 
> Also, I will update how to build more easy



>

**Comment by liuypcoding** [comment]
Thanks!!  I had installed Autoware.Universe  and success run the Autoware Documentation tutorials.
I want to use it with simulator . But autowarefoundation Under construction .

Which simulator for Autoware.Universe would you recommend for perception and vehicle dynamics simulation now.  

 Best Which!! Thank you

**Comment by yukkysaito** [comment]
> Which simulator for Autoware.Universe would you recommend for perception and vehicle dynamics simulation now.
Now, only supported rosbag replay simulator and planning simulator officially.

A Unity-based simulator will be available on Autoware soon.
https://discord.com/channels/953808765935816715/953901404727148574

**Comment by mitsudome-r** [comment]
It's now available in https://autowarefoundation.github.io/autoware-documentation/main/tutorials/digital-twin-simulation/awsim-tutorial/

**Comment by liuypcoding** [comment]
> 它现在在[https://autowarefoundation.github.io/autoware-documentation/main/tutorials/digital-twin-

simulation/awsim-tutorial/中可用](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/digital-twin-simulation/awsim-tutorial/)

Wonderful !!     it's just what I had in mind. I will try it !

Thanks a million

**Comment by yukkysaito** [comment]
@liuypcoding 
I added the visualization code for traffic light
https://github.com/yukkysaito/godot_rviz2/commit/aedcc525e9b9698aaf0b4171b34164ef74977fc1

![image](https://user-images.githubusercontent.com/8327598/181913821-5f1dc0b2-1484-42a4-a233-ee0c044bbaea.png)
